import os;

ACCESS_CODE =''  #ACCESS CODE FROM META
PHONE_ID = '' #PHONE NUMBER ID FROM META
DB_FILE = "buses.db"

#ADMIN CREDENTIALS 
ADMIN_USERNAME = os.getenv("ADMIN_USER")
ADMIN_PASSWORD = os.getenv("ADMIN_PASS")
